# Generated by Django 5.0.7 on 2024-07-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_unit_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
