# Generated by Django 5.0.7 on 2024-07-14 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outbound', '0002_alter_stock_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('outbound_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbound.outbound')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbound.stock')),
            ],
        ),
        migrations.AddField(
            model_name='outbound',
            name='items',
            field=models.ManyToManyField(through='outbound.OutboundItem', to='outbound.stock'),
        ),
    ]
