# Generated by Django 5.0.7 on 2024-07-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='transaction_ref',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
