# Generated by Django 5.0.7 on 2024-07-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0002_alter_outbound_transaction_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='customer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
