# Generated by Django 5.0.7 on 2024-07-15 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0004_outbound_unit'),
        ('profiles', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbounditem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.unit'),
        ),
    ]
