# Generated by Django 5.0.7 on 2024-07-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
